#!/bin/bash
if [ "$HOSTNAME" = "wyvern" ]; then
    python="$HOME/gits/pyenv/versions/3.9.1/bin/python"
else
    python="$HOME/.pyenv/versions/3.9.1/bin/python"
fi

$python $HOME/gits/allred/simcompanies/fetch_random_resource.py
